### ISSUE TITLE
How to configure communication over internet

### ISSUE THREAD

**Issue by wutianze** [ihmcrobotics/ihmc-pub-sub-group#9]
Thanks for your work!
I want to know how to configure the IP address for participant so that the Reader and Writer can communicate over the internet. Should I use `bindToAddress` and please teach me how to use it.
Thank you so much.

**Comment by jespersmith** [comment]
Unfortunately I've not tested/implemented this. `bindToAddress`  binds to a local port, but to connect over WAN you'll have to set an initial peer.

We'll have to add this as an easy-to-use function in a next release.

I think the easiest way to do this is to use the FastRTPS xml profiles (https://fast-rtps.docs.eprosima.com/en/v1.7.0/xmlprofiles.html#participant-profiles). You'll want to put the xml profile in the working directory of your java program, named "DEFAULT_FASTRTPS_PROFILES.xml". I think you'll have to set an initialPeerList in the builtin attributes

Another way to set the builtin attributes is to get the RTPSParticipantAttributes directly using 

```
FastRTPSParticipantAttributes attr = (FastRTPSParticipantAttributes) domain.createParticipantAttributes();
RTPSParticipantAttributes rtps = attr.rtps();

BuiltinAttributes builtin = rtps.getBuiltin();

Locator_t locator = .... 
builtin.getInitialPeersList().push_back(locator);
```

To create a locator_t type, please see `FastRTPSCommonFunctions.convertToCPPLocator()`. Unfortunately this class is package-private and not easy to use.

**Comment by wutianze** [comment]
Thank you! I will try this.
